[phases.setup]
nixPkgs = ["php84", "php84Extensions...", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --ignore-platform-reqs",
    "npm i"
]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"